site_name: "SQIL core"

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  homepage: https://www.epfl.ch/labs/sqil/research/

markdown_extensions:
  - toc:
      toc_depth: 2
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
            python:
              options:
                docstring_style: numpy

nav:
  - Getting started: index.md
  - Notebooks:
    - The fit_output decorator: 'Notebooks/fit_output_decorator.ipynb'
  - API reference:
    - Fit:
      - Core: 'API reference/fit/core.md'
      - Fit: 'API reference/fit/fit.md'
    - Resonator: 'API reference/resonator/resonator.md'
    - Utilies:
      - Read data: 'API reference/utils/read data.md'
      - Formatter: 'API reference/utils/formatter.md'
      - Analysis: 'API reference/utils/analysis.md'