name: Publish Package

on:
  # Trigger when a tag is pushed (usually a version bump like v1.0.0)
  push:
    tags:
      - 'v*'  # You can adjust the tag pattern as needed (e.g., v1.0.0)

  # Trigger when the "Check formatting and run tests" workflow completes
  workflow_run:
    workflows: ["Check formatting and run tests"]
    types:
      - completed

jobs:
  publish:
    # Run the job only if the previous workflow was successful (for `workflow_run` event)
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }} 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi

    - name: Build the package
      run: poetry build

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
        poetry publish --build --no-interaction --no-ansi
